/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-11-18 12:43:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.io.File;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1,user-scalable=no\">\n");
      out.write("<!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->\n");
      out.write("<title>主页</title>\n");
      out.write("<!-- Bootstrap -->\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"jquery-easyui-1.4.4/themes/default/easyui.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"jquery-easyui-1.4.4/themes/icon.css\">\n");
      out.write("<!--<script type=\"text/javascript\" src=\"jquery-easyui-1.4.4/jquery.min.js\"></script>-->\n");
      out.write("<script src=\"js/jquery-1.11.3.min.js\" type=\"text/javascript\"\n");
      out.write("\tcharset=\"utf-8\"></script>\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("\tsrc=\"jquery-easyui-1.4.4/jquery.easyui.min.js\"></script>\n");
      out.write("<script src=\"bootstrap-3.3.5-dist/js/bootstrap.min.js\"\n");
      out.write("\ttype=\"text/javascript\" charset=\"utf-8\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"bootstrap-3.3.5-dist/css/bootstrap.min.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/layout_index.css\" />\n");
      out.write("<script type=\"text/javascript\" src=\"js/index.js\"></script>\n");
      out.write("<!--HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries-->\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("<!--[if lt IE 9]>\n");
      out.write("      <script src=\"//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n");
      out.write("      <script src=\"//cdn.bootcss.com/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t");

		request.setCharacterEncoding("utf-8");
		String fileadd = config.getServletContext().getInitParameter("file");
	
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"navbar navbar-default  navbar-fixed-top\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t<span class=\"navbar-brand\"> Andriod班网盘 </span>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"col-lg-offset-5 col-lg-2\">\n");
      out.write("\t\t\t<form class=\"navbar-form\" role=\"search\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"input-group\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control \" name=\"searchs\"\n");
      out.write("\t\t\t\t\t\t\tid=\"searchs\" placeholder=\"文章.标题.内容\" /> <span\n");
      out.write("\t\t\t\t\t\t\tclass=\"input-group-btn\"> <input type=\"button\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-default\" value=\"搜索\" />\n");
      out.write("\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<div class=\"dright\">\n");
      out.write("\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav \">\n");
      out.write("\n");
      out.write("\t\t\t\t<li><a href=\"javascript:void(0)\"><span class=\"user\">\n");
      out.write("\t\t\t\t\t\t\t");

								Object user = session.getAttribute("username");
								if (user != null) {
									String userStr = (String) user;
									out.println(userStr);
								} else {
									response.sendRedirect("login.jsp");
								}
							
      out.write("\n");
      out.write("\t\t\t\t\t</span> </a></li>\n");
      out.write("\t\t\t\t<li><a href=\"javascript:void(0)\">会员中心</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"javascript:void(0)\">客户端下载</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"javascript:void(0)\">通知</a></li>\n");
      out.write("\n");
      out.write("\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"contain\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-lg-offset-1 col-lg-3\">\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\n");
      out.write("\t\t\t\t\t<div class=\"panel-body tree\">\n");
      out.write("\t\t\t\t\t\t<ul id=\"tt\"></ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-lg-7\">\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary\" type=\"button\" name=\"upload\"\n");
      out.write("\t\t\t\t\t\t\tid=\"upload\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-open\"> </span>上传文件\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default create\" type=\"button\" name=\"create\"\n");
      out.write("\t\t\t\t\t\t\tid=\"create\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-plus\"> </span>新建文件夹\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t<div class=\"text\">\n");
      out.write("\t\t\t\t\t\t\t<a class=\"backIndex\" href=\"javascript:void(0)\">全部文件</a> <a\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"back\" href=\"javascript:void(0)\">返回上级</a> \n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"thisLoc\"></a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"tables\">\n");
      out.write("\t\t\t\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t\t\t\t<tbody class=\"tabs\" address=");
      out.print(fileadd);
      out.write(">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t\t\t\t</table>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"texts\"></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("<!--模态窗口-->\n");
      out.write("\t\t<div id=\"wids\" class=\"modal fade\" role=\"dialog\" aria-labelledby=\"myTextarea\">\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
