/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-11-20 13:26:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1,user-scalable=no\">\n");
      out.write("<!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->\n");
      out.write("<title>登录</title>\n");
      out.write("<!-- Bootstrap -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/layout_login.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"bootstrap-3.3.5-dist/css/bootstrap.min.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"bootstrap-3.3.5-dist/css/bootstrap-theme.css\" />\n");
      out.write("<script src=\"js/jquery-1.11.3.min.js\" type=\"text/javascript\"\n");
      out.write("\tcharset=\"utf-8\"></script>\n");
      out.write("<script src=\"js/jquery-migrate-1.2.1.min.js\" type=\"text/javascript\"\n");
      out.write("\tcharset=\"utf-8\"></script>\n");
      out.write("<script src=\"js/login.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\n");
      out.write("<script src=\"bootstrap-3.3.5-dist/js/bootstrap.min.js\"\n");
      out.write("\ttype=\"text/javascript\" charset=\"utf-8\"></script>\n");
      out.write("<!--HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries-->\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("<!--[if lt IE 9]>\n");
      out.write("      <script src=\"//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n");
      out.write("      <script src=\"//cdn.bootcss.com/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t");

		String vlu="";
		Cookie[] cookie = request.getCookies();
		if (cookie != null) {
			for (Cookie c : cookie) {
				if (c.getName().equals("username")) {
					vlu = c.getValue();
				}
			}
		}
	
      out.write("\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"navbar navbar-default  navbar-fixed-top\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t\t\t<span class=\"navbar-brand\"> Andriod班网盘 </span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-offset-10\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav \">\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"#\">首页 </a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"bbs.html\">贴吧</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">微博</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"photos col-lg-8\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div id=\"carousel-example-generics\" class=\"carousel slide\"\n");
      out.write("\t\t\t\t\tdata-ride=\"carousel\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<ol class=\"carousel-indicators\">\n");
      out.write("\t\t\t\t\t\t<li data-target=\"#carousel-example-generic\" data-slide-to=\"0\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"active\"></li>\n");
      out.write("\t\t\t\t\t\t<li data-target=\"#carousel-example-generic\" data-slide-to=\"1\"></li>\n");
      out.write("\t\t\t\t\t\t<li data-target=\"#carousel-example-generic\" data-slide-to=\"2\"></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</ol>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"carousel-inner\" role=\"listbox\">\n");
      out.write("\t\t\t\t\t\t<div class=\"item active\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/1.png\" alt=\"...\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/2.jpg\" alt=\"...\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/1.png\" alt=\"...\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"photos col-lg-offset-0 col-lg-4\">\n");
      out.write("\t\t\t\t<div class=\"panel panel-default panelLogin\">\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t<form action=\"loginaction.jsp\" class=\"form\" method=\"post\">\n");
      out.write("\t\t\t\t\t\t\t<h1>请登录帐号</h1>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon \" id=\"basic-addon1\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"> </span></span> <input id=\"username\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"username\" type=\"text\" value=\"");
      out.print(vlu);
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"用户名\" />\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon \" id=\"basic-addon1\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-lock\"> </span></span> <input\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"password\" id=\"password\" name=\"password\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"密码\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"cboxremb\" type=\"checkbox\"></input> <a\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"rema\">记住密码</a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"sub\" type=\"submit\" class=\"btn btn-primary btn-block\"\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"登录\" /> <input id=\"log\" type=\"button\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-primary btn-block reg\" value=\"注册\" /> <span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"info\"></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
